/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoSetTagReq {
    #[serde(rename = "increaseUserIDList", skip_serializing_if = "Option::is_none")]
    pub increase_user_id_list: Option<Vec<String>>,
    #[serde(rename = "newName", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "reduceUserIDList", skip_serializing_if = "Option::is_none")]
    pub reduce_user_id_list: Option<Vec<String>>,
    #[serde(rename = "tagID")]
    pub tag_id: String,
}

impl BaseInfoSetTagReq {
    pub fn new(operation_id: String, tag_id: String) -> BaseInfoSetTagReq {
        BaseInfoSetTagReq {
            increase_user_id_list: None,
            new_name: None,
            operation_id,
            reduce_user_id_list: None,
            tag_id,
        }
    }
}


