/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGetTagSendLogsReq {
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "pageNumber")]
    pub page_number: i32,
    #[serde(rename = "showNumber")]
    pub show_number: i32,
}

impl BaseInfoGetTagSendLogsReq {
    pub fn new(operation_id: String, page_number: i32, show_number: i32) -> BaseInfoGetTagSendLogsReq {
        BaseInfoGetTagSendLogsReq {
            operation_id,
            page_number,
            show_number,
        }
    }
}


