/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoJoinGroupReq {
    #[serde(rename = "groupID")]
    pub group_id: String,
    #[serde(rename = "inviterUserID", skip_serializing_if = "Option::is_none")]
    pub inviter_user_id: Option<String>,
    #[serde(rename = "joinSource", skip_serializing_if = "Option::is_none")]
    pub join_source: Option<i32>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "reqMessage", skip_serializing_if = "Option::is_none")]
    pub req_message: Option<String>,
}

impl BaseInfoJoinGroupReq {
    pub fn new(group_id: String, operation_id: String) -> BaseInfoJoinGroupReq {
        BaseInfoJoinGroupReq {
            group_id,
            inviter_user_id: None,
            join_source: None,
            operation_id,
            req_message: None,
        }
    }
}


