/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoDeleteDepartmentReq {
    #[serde(rename = "departmentID")]
    pub department_id: String,
    #[serde(rename = "operationID")]
    pub operation_id: String,
}

impl BaseInfoDeleteDepartmentReq {
    pub fn new(department_id: String, operation_id: String) -> BaseInfoDeleteDepartmentReq {
        BaseInfoDeleteDepartmentReq {
            department_id,
            operation_id,
        }
    }
}


