/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoCreateGroupReq {
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "faceURL", skip_serializing_if = "Option::is_none")]
    pub face_url: Option<String>,
    #[serde(rename = "groupID", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    #[serde(rename = "groupName", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    #[serde(rename = "groupType", skip_serializing_if = "Option::is_none")]
    pub group_type: Option<i32>,
    #[serde(rename = "introduction", skip_serializing_if = "Option::is_none")]
    pub introduction: Option<String>,
    #[serde(rename = "memberList", skip_serializing_if = "Option::is_none")]
    pub member_list: Option<Vec<crate::models::BaseInfoGroupAddMemberInfo>>,
    #[serde(rename = "notification", skip_serializing_if = "Option::is_none")]
    pub notification: Option<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "ownerUserID", skip_serializing_if = "Option::is_none")]
    pub owner_user_id: Option<String>,
}

impl BaseInfoCreateGroupReq {
    pub fn new(operation_id: String) -> BaseInfoCreateGroupReq {
        BaseInfoCreateGroupReq {
            ex: None,
            face_url: None,
            group_id: None,
            group_name: None,
            group_type: None,
            introduction: None,
            member_list: None,
            notification: None,
            operation_id,
            owner_user_id: None,
        }
    }
}


