/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoUpdateDepartmentReq {
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i32>,
    #[serde(rename = "departmentID")]
    pub department_id: String,
    #[serde(rename = "departmentType", skip_serializing_if = "Option::is_none")]
    pub department_type: Option<i32>,
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "faceURL", skip_serializing_if = "Option::is_none")]
    pub face_url: Option<String>,
    #[serde(rename = "memberNum", skip_serializing_if = "Option::is_none")]
    pub member_num: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
    #[serde(rename = "parentID", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "subDepartmentNum", skip_serializing_if = "Option::is_none")]
    pub sub_department_num: Option<i32>,
}

impl BaseInfoUpdateDepartmentReq {
    pub fn new(department_id: String, operation_id: String) -> BaseInfoUpdateDepartmentReq {
        BaseInfoUpdateDepartmentReq {
            create_time: None,
            department_id,
            department_type: None,
            ex: None,
            face_url: None,
            member_num: None,
            name: None,
            operation_id,
            order: None,
            parent_id: None,
            sub_department_num: None,
        }
    }
}


