/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGetWorkMomentByIdRespData {
    #[serde(rename = "workMoment", skip_serializing_if = "Option::is_none")]
    pub work_moment: Option<crate::models::BaseInfoWorkMoment>,
}

impl BaseInfoGetWorkMomentByIdRespData {
    pub fn new() -> BaseInfoGetWorkMomentByIdRespData {
        BaseInfoGetWorkMomentByIdRespData {
            work_moment: None,
        }
    }
}


