/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoUserTokenInfo {
    #[serde(rename = "expiredTime", skip_serializing_if = "Option::is_none")]
    pub expired_time: Option<i32>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl BaseInfoUserTokenInfo {
    pub fn new() -> BaseInfoUserTokenInfo {
        BaseInfoUserTokenInfo {
            expired_time: None,
            token: None,
            user_id: None,
        }
    }
}


