/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoLikeOneWorkMomentReq {
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "workMomentID")]
    pub work_moment_id: String,
}

impl BaseInfoLikeOneWorkMomentReq {
    pub fn new(operation_id: String, work_moment_id: String) -> BaseInfoLikeOneWorkMomentReq {
        BaseInfoLikeOneWorkMomentReq {
            operation_id,
            work_moment_id,
        }
    }
}


