/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoDeleteFriendReq {
    #[serde(rename = "fromUserID")]
    pub from_user_id: String,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "toUserID")]
    pub to_user_id: String,
}

impl BaseInfoDeleteFriendReq {
    pub fn new(from_user_id: String, operation_id: String, to_user_id: String) -> BaseInfoDeleteFriendReq {
        BaseInfoDeleteFriendReq {
            from_user_id,
            operation_id,
            to_user_id,
        }
    }
}


