/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoCreateOneWorkMomentReq {
    #[serde(rename = "operationID", skip_serializing_if = "Option::is_none")]
    pub operation_id: Option<String>,
    #[serde(rename = "workMoment", skip_serializing_if = "Option::is_none")]
    pub work_moment: Option<crate::models::OfficeWorkMoment>,
}

impl BaseInfoCreateOneWorkMomentReq {
    pub fn new() -> BaseInfoCreateOneWorkMomentReq {
        BaseInfoCreateOneWorkMomentReq {
            operation_id: None,
            work_moment: None,
        }
    }
}


