/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoSetGroupInfoReq {
    #[serde(rename = "applyMemberFriend", skip_serializing_if = "Option::is_none")]
    pub apply_member_friend: Option<i32>,
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "faceURL", skip_serializing_if = "Option::is_none")]
    pub face_url: Option<String>,
    #[serde(rename = "groupID")]
    pub group_id: String,
    #[serde(rename = "groupName", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    #[serde(rename = "introduction", skip_serializing_if = "Option::is_none")]
    pub introduction: Option<String>,
    #[serde(rename = "lookMemberInfo", skip_serializing_if = "Option::is_none")]
    pub look_member_info: Option<i32>,
    #[serde(rename = "needVerification", skip_serializing_if = "Option::is_none")]
    pub need_verification: Option<i32>,
    #[serde(rename = "notification", skip_serializing_if = "Option::is_none")]
    pub notification: Option<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
}

impl BaseInfoSetGroupInfoReq {
    pub fn new(group_id: String, operation_id: String) -> BaseInfoSetGroupInfoReq {
        BaseInfoSetGroupInfoReq {
            apply_member_friend: None,
            ex: None,
            face_url: None,
            group_id,
            group_name: None,
            introduction: None,
            look_member_info: None,
            need_verification: None,
            notification: None,
            operation_id,
        }
    }
}


