/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoCreateTagReq {
    #[serde(rename = "operationID")]
    pub operation_id: String,
    /// tag名称
    #[serde(rename = "tagName")]
    pub tag_name: String,
    /// 用户ID列表
    #[serde(rename = "userIDList")]
    pub user_id_list: Vec<String>,
}

impl BaseInfoCreateTagReq {
    pub fn new(operation_id: String, tag_name: String, user_id_list: Vec<String>) -> BaseInfoCreateTagReq {
        BaseInfoCreateTagReq {
            operation_id,
            tag_name,
            user_id_list,
        }
    }
}


