/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGetUserTagByIdRespData {
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<crate::models::OfficeTag>,
}

impl BaseInfoGetUserTagByIdRespData {
    pub fn new() -> BaseInfoGetUserTagByIdRespData {
        BaseInfoGetUserTagByIdRespData {
            tag: None,
        }
    }
}


