/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGroupAddMemberInfo {
    #[serde(rename = "roleLevel")]
    pub role_level: RoleLevel,
    #[serde(rename = "userID")]
    pub user_id: String,
}

impl BaseInfoGroupAddMemberInfo {
    pub fn new(role_level: RoleLevel, user_id: String) -> BaseInfoGroupAddMemberInfo {
        BaseInfoGroupAddMemberInfo {
            role_level,
            user_id,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoleLevel {
    #[serde(rename = "1")]
    _1,
    #[serde(rename = "3")]
    _3,
}

