/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGetGroupAllMemberReq {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "groupID")]
    pub group_id: String,
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "operationID")]
    pub operation_id: String,
}

impl BaseInfoGetGroupAllMemberReq {
    pub fn new(count: i32, group_id: String, offset: i32, operation_id: String) -> BaseInfoGetGroupAllMemberReq {
        BaseInfoGetGroupAllMemberReq {
            count,
            group_id,
            offset,
            operation_id,
        }
    }
}


