/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoCommentOneWorkMomentReq {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "replyUserID", skip_serializing_if = "Option::is_none")]
    pub reply_user_id: Option<String>,
    #[serde(rename = "workMomentID")]
    pub work_moment_id: String,
}

impl BaseInfoCommentOneWorkMomentReq {
    pub fn new(content: String, operation_id: String, work_moment_id: String) -> BaseInfoCommentOneWorkMomentReq {
        BaseInfoCommentOneWorkMomentReq {
            content,
            operation_id,
            reply_user_id: None,
            work_moment_id,
        }
    }
}


