/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoAddFriendResponseReq {
    #[serde(rename = "flag")]
    pub flag: Flag,
    #[serde(rename = "fromUserID")]
    pub from_user_id: String,
    #[serde(rename = "handleMsg", skip_serializing_if = "Option::is_none")]
    pub handle_msg: Option<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "toUserID")]
    pub to_user_id: String,
}

impl BaseInfoAddFriendResponseReq {
    pub fn new(flag: Flag, from_user_id: String, operation_id: String, to_user_id: String) -> BaseInfoAddFriendResponseReq {
        BaseInfoAddFriendResponseReq {
            flag,
            from_user_id,
            handle_msg: None,
            operation_id,
            to_user_id,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Flag {
    #[serde(rename = "-1")]
    _1,
    #[serde(rename = "0")]
    _0,
    // #[serde(rename = "1")]
    // _1,
}

