/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoConversation {
    #[serde(rename = "attachedInfo", skip_serializing_if = "Option::is_none")]
    pub attached_info: Option<String>,
    #[serde(rename = "conversationID")]
    pub conversation_id: String,
    #[serde(rename = "conversationType")]
    pub conversation_type: i32,
    #[serde(rename = "draftTextTime", skip_serializing_if = "Option::is_none")]
    pub draft_text_time: Option<i32>,
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "groupAtType", skip_serializing_if = "Option::is_none")]
    pub group_at_type: Option<i32>,
    #[serde(rename = "groupID", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    #[serde(rename = "isNotInGroup", skip_serializing_if = "Option::is_none")]
    pub is_not_in_group: Option<bool>,
    #[serde(rename = "isPinned", skip_serializing_if = "Option::is_none")]
    pub is_pinned: Option<bool>,
    #[serde(rename = "isPrivateChat", skip_serializing_if = "Option::is_none")]
    pub is_private_chat: Option<bool>,
    #[serde(rename = "ownerUserID")]
    pub owner_user_id: String,
    #[serde(rename = "recvMsgOpt", skip_serializing_if = "Option::is_none")]
    pub recv_msg_opt: Option<RecvMsgOpt>,
    #[serde(rename = "unreadCount", skip_serializing_if = "Option::is_none")]
    pub unread_count: Option<i32>,
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl BaseInfoConversation {
    pub fn new(conversation_id: String, conversation_type: i32, owner_user_id: String) -> BaseInfoConversation {
        BaseInfoConversation {
            attached_info: None,
            conversation_id,
            conversation_type,
            draft_text_time: None,
            ex: None,
            group_at_type: None,
            group_id: None,
            is_not_in_group: None,
            is_pinned: None,
            is_private_chat: None,
            owner_user_id,
            recv_msg_opt: None,
            unread_count: None,
            user_id: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecvMsgOpt {
    #[serde(rename = "0")]
    _0,
    #[serde(rename = "1")]
    _1,
    #[serde(rename = "2")]
    _2,
}

