/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoDelMsgReq {
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "seqList")]
    pub seq_list: Vec<i32>,
    #[serde(rename = "userID")]
    pub user_id: String,
}

impl BaseInfoDelMsgReq {
    pub fn new(operation_id: String, seq_list: Vec<i32>, user_id: String) -> BaseInfoDelMsgReq {
        BaseInfoDelMsgReq {
            operation_id,
            seq_list,
            user_id,
        }
    }
}


