/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGetGroupMembersInfoReq {
    #[serde(rename = "groupID")]
    pub group_id: String,
    #[serde(rename = "memberList")]
    pub member_list: Vec<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
}

impl BaseInfoGetGroupMembersInfoReq {
    pub fn new(group_id: String, member_list: Vec<String>, operation_id: String) -> BaseInfoGetGroupMembersInfoReq {
        BaseInfoGetGroupMembersInfoReq {
            group_id,
            member_list,
            operation_id,
        }
    }
}


