/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoUserRegisterReq {
    #[serde(rename = "birth", skip_serializing_if = "Option::is_none")]
    pub birth: Option<i32>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "faceURL", skip_serializing_if = "Option::is_none")]
    pub face_url: Option<String>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<Gender>,
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "platform")]
    pub platform: i32,
    #[serde(rename = "secret")]
    pub secret: String,
    #[serde(rename = "userID")]
    pub user_id: String,
}

impl BaseInfoUserRegisterReq {
    pub fn new(operation_id: String, platform: i32, secret: String, user_id: String) -> BaseInfoUserRegisterReq {
        BaseInfoUserRegisterReq {
            birth: None,
            email: None,
            ex: None,
            face_url: None,
            gender: None,
            nickname: None,
            operation_id,
            phone_number: None,
            platform,
            secret,
            user_id,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Gender {
    #[serde(rename = "0")]
    _0,
    #[serde(rename = "1")]
    _1,
    #[serde(rename = "2")]
    _2,
}

