/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoAddFriendReq {
    #[serde(rename = "fromUserID")]
    pub from_user_id: String,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "reqMsg", skip_serializing_if = "Option::is_none")]
    pub req_msg: Option<String>,
    #[serde(rename = "toUserID")]
    pub to_user_id: String,
}

impl BaseInfoAddFriendReq {
    pub fn new(from_user_id: String, operation_id: String, to_user_id: String) -> BaseInfoAddFriendReq {
        BaseInfoAddFriendReq {
            from_user_id,
            operation_id,
            req_msg: None,
            to_user_id,
        }
    }
}


