/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGetTagSendLogsRespData {
    #[serde(rename = "currentPage", skip_serializing_if = "Option::is_none")]
    pub current_page: Option<i32>,
    #[serde(rename = "logs", skip_serializing_if = "Option::is_none")]
    pub logs: Option<Vec<crate::models::OfficeTagSendLog>>,
    #[serde(rename = "showNumber", skip_serializing_if = "Option::is_none")]
    pub show_number: Option<i32>,
}

impl BaseInfoGetTagSendLogsRespData {
    pub fn new() -> BaseInfoGetTagSendLogsRespData {
        BaseInfoGetTagSendLogsRespData {
            current_page: None,
            logs: None,
            show_number: None,
        }
    }
}


