/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGetConversationsReq {
    #[serde(rename = "conversationIDs")]
    pub conversation_i_ds: Vec<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "ownerUserID")]
    pub owner_user_id: String,
}

impl BaseInfoGetConversationsReq {
    pub fn new(conversation_i_ds: Vec<String>, operation_id: String, owner_user_id: String) -> BaseInfoGetConversationsReq {
        BaseInfoGetConversationsReq {
            conversation_i_ds,
            operation_id,
            owner_user_id,
        }
    }
}


