/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoAccountCheckReq {
    #[serde(rename = "checkUserIDList")]
    pub check_user_id_list: Vec<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
}

impl BaseInfoAccountCheckReq {
    pub fn new(check_user_id_list: Vec<String>, operation_id: String) -> BaseInfoAccountCheckReq {
        BaseInfoAccountCheckReq {
            check_user_id_list,
            operation_id,
        }
    }
}


