/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGetUserWorkMomentsRespData {
    #[serde(rename = "currentPage", skip_serializing_if = "Option::is_none")]
    pub current_page: Option<i32>,
    #[serde(rename = "showNumber", skip_serializing_if = "Option::is_none")]
    pub show_number: Option<i32>,
    #[serde(rename = "workMoments", skip_serializing_if = "Option::is_none")]
    pub work_moments: Option<Vec<crate::models::BaseInfoWorkMoment>>,
}

impl BaseInfoGetUserWorkMomentsRespData {
    pub fn new() -> BaseInfoGetUserWorkMomentsRespData {
        BaseInfoGetUserWorkMomentsRespData {
            current_page: None,
            show_number: None,
            work_moments: None,
        }
    }
}


