/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoGetGroupApplicationListReq {
    /// 作为管理员或群主收到的 进群申请
    #[serde(rename = "fromUserID")]
    pub from_user_id: String,
    #[serde(rename = "operationID")]
    pub operation_id: String,
}

impl BaseInfoGetGroupApplicationListReq {
    pub fn new(from_user_id: String, operation_id: String) -> BaseInfoGetGroupApplicationListReq {
        BaseInfoGetGroupApplicationListReq {
            from_user_id,
            operation_id,
        }
    }
}


