/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoSetGlobalRecvMessageOptReq {
    #[serde(rename = "globalRecvMsgOpt", skip_serializing_if = "Option::is_none")]
    pub global_recv_msg_opt: Option<GlobalRecvMsgOpt>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
}

impl BaseInfoSetGlobalRecvMessageOptReq {
    pub fn new(operation_id: String) -> BaseInfoSetGlobalRecvMessageOptReq {
        BaseInfoSetGlobalRecvMessageOptReq {
            global_recv_msg_opt: None,
            operation_id,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GlobalRecvMsgOpt {
    #[serde(rename = "0")]
    _0,
    #[serde(rename = "1")]
    _1,
    #[serde(rename = "2")]
    _2,
}

