/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseInfoSetGroupMemberInfoReq {
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "groupID")]
    pub group_id: String,
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    #[serde(rename = "operationID")]
    pub operation_id: String,
    #[serde(rename = "roleLevel", skip_serializing_if = "Option::is_none")]
    pub role_level: Option<i32>,
    #[serde(rename = "userGroupFaceUrl", skip_serializing_if = "Option::is_none")]
    pub user_group_face_url: Option<String>,
    #[serde(rename = "userID")]
    pub user_id: String,
}

impl BaseInfoSetGroupMemberInfoReq {
    pub fn new(group_id: String, operation_id: String, user_id: String) -> BaseInfoSetGroupMemberInfoReq {
        BaseInfoSetGroupMemberInfoReq {
            ex: None,
            group_id,
            nickname: None,
            operation_id,
            role_level: None,
            user_group_face_url: None,
            user_id,
        }
    }
}


