/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject {
    /// 要上传的文件文件
    #[serde(rename = "file")]
    pub file: std::path::PathBuf,
    /// 文件类型
    #[serde(rename = "fileType")]
    pub file_type: i32,
    /// 操作唯一ID
    #[serde(rename = "operationID")]
    pub operation_id: String,
}

impl InlineObject {
    pub fn new(file: std::path::PathBuf, file_type: i32, operation_id: String) -> InlineObject {
        InlineObject {
            file,
            file_type,
            operation_id,
        }
    }
}


