/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InternalApiManageOaNotificationElem {
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "fileElem", skip_serializing_if = "Option::is_none")]
    pub file_elem: Option<crate::models::InternalApiManageFileElem>,
    #[serde(rename = "mixType", skip_serializing_if = "Option::is_none")]
    pub mix_type: Option<i32>,
    #[serde(rename = "notificationFaceURL", skip_serializing_if = "Option::is_none")]
    pub notification_face_url: Option<String>,
    #[serde(rename = "notificationName")]
    pub notification_name: String,
    #[serde(rename = "notificationType")]
    pub notification_type: i32,
    #[serde(rename = "pictureElem", skip_serializing_if = "Option::is_none")]
    pub picture_elem: Option<crate::models::InternalApiManagePictureElem>,
    #[serde(rename = "soundElem", skip_serializing_if = "Option::is_none")]
    pub sound_elem: Option<crate::models::InternalApiManageSoundElem>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "videoElem", skip_serializing_if = "Option::is_none")]
    pub video_elem: Option<crate::models::InternalApiManageVideoElem>,
}

impl InternalApiManageOaNotificationElem {
    pub fn new(notification_name: String, notification_type: i32, text: String) -> InternalApiManageOaNotificationElem {
        InternalApiManageOaNotificationElem {
            ex: None,
            file_elem: None,
            mix_type: None,
            notification_face_url: None,
            notification_name,
            notification_type,
            picture_elem: None,
            sound_elem: None,
            text,
            url: None,
            video_elem: None,
        }
    }
}


