/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InternalApiManageVideoElem {
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    #[serde(rename = "snapshotHeight", skip_serializing_if = "Option::is_none")]
    pub snapshot_height: Option<i32>,
    #[serde(rename = "snapshotPath", skip_serializing_if = "Option::is_none")]
    pub snapshot_path: Option<String>,
    #[serde(rename = "snapshotSize", skip_serializing_if = "Option::is_none")]
    pub snapshot_size: Option<i32>,
    #[serde(rename = "snapshotURL", skip_serializing_if = "Option::is_none")]
    pub snapshot_url: Option<String>,
    #[serde(rename = "snapshotUUID", skip_serializing_if = "Option::is_none")]
    pub snapshot_uuid: Option<String>,
    #[serde(rename = "snapshotWidth", skip_serializing_if = "Option::is_none")]
    pub snapshot_width: Option<i32>,
    #[serde(rename = "videoPath", skip_serializing_if = "Option::is_none")]
    pub video_path: Option<String>,
    #[serde(rename = "videoSize", skip_serializing_if = "Option::is_none")]
    pub video_size: Option<i32>,
    #[serde(rename = "videoType", skip_serializing_if = "Option::is_none")]
    pub video_type: Option<String>,
    #[serde(rename = "videoURL", skip_serializing_if = "Option::is_none")]
    pub video_url: Option<String>,
    #[serde(rename = "videoUUID", skip_serializing_if = "Option::is_none")]
    pub video_uuid: Option<String>,
}

impl InternalApiManageVideoElem {
    pub fn new() -> InternalApiManageVideoElem {
        InternalApiManageVideoElem {
            duration: None,
            snapshot_height: None,
            snapshot_path: None,
            snapshot_size: None,
            snapshot_url: None,
            snapshot_uuid: None,
            snapshot_width: None,
            video_path: None,
            video_size: None,
            video_type: None,
            video_url: None,
            video_uuid: None,
        }
    }
}


