/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfficeTagSendLog {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "sendTime", skip_serializing_if = "Option::is_none")]
    pub send_time: Option<i32>,
    #[serde(rename = "userList", skip_serializing_if = "Option::is_none")]
    pub user_list: Option<Vec<crate::models::OfficeTagUser>>,
}

impl OfficeTagSendLog {
    pub fn new() -> OfficeTagSendLog {
        OfficeTagSendLog {
            content: None,
            send_time: None,
            user_list: None,
        }
    }
}


