/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfficeTag {
    #[serde(rename = "tagID", skip_serializing_if = "Option::is_none")]
    pub tag_id: Option<String>,
    #[serde(rename = "tagName", skip_serializing_if = "Option::is_none")]
    pub tag_name: Option<String>,
    #[serde(rename = "userList", skip_serializing_if = "Option::is_none")]
    pub user_list: Option<Vec<crate::models::OfficeTagUser>>,
}

impl OfficeTag {
    pub fn new() -> OfficeTag {
        OfficeTag {
            tag_id: None,
            tag_name: None,
            user_list: None,
        }
    }
}


