/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PbRelayGetUsersOnlineStatusRespSuccessDetail {
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl PbRelayGetUsersOnlineStatusRespSuccessDetail {
    pub fn new() -> PbRelayGetUsersOnlineStatusRespSuccessDetail {
        PbRelayGetUsersOnlineStatusRespSuccessDetail {
            platform: None,
            status: None,
        }
    }
}


