/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerApiParamsFriendInfo {
    #[serde(rename = "addSource", skip_serializing_if = "Option::is_none")]
    pub add_source: Option<i32>,
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i32>,
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "friendUser", skip_serializing_if = "Option::is_none")]
    pub friend_user: Option<crate::models::ServerApiParamsUserInfo>,
    #[serde(rename = "operatorUserID", skip_serializing_if = "Option::is_none")]
    pub operator_user_id: Option<String>,
    #[serde(rename = "ownerUserID", skip_serializing_if = "Option::is_none")]
    pub owner_user_id: Option<String>,
    #[serde(rename = "remark", skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
}

impl ServerApiParamsFriendInfo {
    pub fn new() -> ServerApiParamsFriendInfo {
        ServerApiParamsFriendInfo {
            add_source: None,
            create_time: None,
            ex: None,
            friend_user: None,
            operator_user_id: None,
            owner_user_id: None,
            remark: None,
        }
    }
}


