/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerApiParamsFriendRequest {
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i32>,
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "fromFaceURL", skip_serializing_if = "Option::is_none")]
    pub from_face_url: Option<String>,
    #[serde(rename = "fromGender", skip_serializing_if = "Option::is_none")]
    pub from_gender: Option<i32>,
    #[serde(rename = "fromNickname", skip_serializing_if = "Option::is_none")]
    pub from_nickname: Option<String>,
    #[serde(rename = "fromUserID", skip_serializing_if = "Option::is_none")]
    pub from_user_id: Option<String>,
    #[serde(rename = "handleMsg", skip_serializing_if = "Option::is_none")]
    pub handle_msg: Option<String>,
    #[serde(rename = "handleResult", skip_serializing_if = "Option::is_none")]
    pub handle_result: Option<i32>,
    #[serde(rename = "handleTime", skip_serializing_if = "Option::is_none")]
    pub handle_time: Option<i32>,
    #[serde(rename = "handlerUserID", skip_serializing_if = "Option::is_none")]
    pub handler_user_id: Option<String>,
    #[serde(rename = "reqMsg", skip_serializing_if = "Option::is_none")]
    pub req_msg: Option<String>,
    #[serde(rename = "toFaceURL", skip_serializing_if = "Option::is_none")]
    pub to_face_url: Option<String>,
    #[serde(rename = "toGender", skip_serializing_if = "Option::is_none")]
    pub to_gender: Option<i32>,
    #[serde(rename = "toNickname", skip_serializing_if = "Option::is_none")]
    pub to_nickname: Option<String>,
    #[serde(rename = "toUserID", skip_serializing_if = "Option::is_none")]
    pub to_user_id: Option<String>,
}

impl ServerApiParamsFriendRequest {
    pub fn new() -> ServerApiParamsFriendRequest {
        ServerApiParamsFriendRequest {
            create_time: None,
            ex: None,
            from_face_url: None,
            from_gender: None,
            from_nickname: None,
            from_user_id: None,
            handle_msg: None,
            handle_result: None,
            handle_time: None,
            handler_user_id: None,
            req_msg: None,
            to_face_url: None,
            to_gender: None,
            to_nickname: None,
            to_user_id: None,
        }
    }
}


