/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerApiParamsGroupRequest {
    #[serde(rename = "ex", skip_serializing_if = "Option::is_none")]
    pub ex: Option<String>,
    #[serde(rename = "groupInfo", skip_serializing_if = "Option::is_none")]
    pub group_info: Option<crate::models::ServerApiParamsGroupInfo>,
    #[serde(rename = "handleMsg", skip_serializing_if = "Option::is_none")]
    pub handle_msg: Option<String>,
    #[serde(rename = "handleResult", skip_serializing_if = "Option::is_none")]
    pub handle_result: Option<i32>,
    #[serde(rename = "handleTime", skip_serializing_if = "Option::is_none")]
    pub handle_time: Option<i32>,
    #[serde(rename = "handleUserID", skip_serializing_if = "Option::is_none")]
    pub handle_user_id: Option<String>,
    #[serde(rename = "inviterUserID", skip_serializing_if = "Option::is_none")]
    pub inviter_user_id: Option<String>,
    #[serde(rename = "joinSource", skip_serializing_if = "Option::is_none")]
    pub join_source: Option<i32>,
    #[serde(rename = "reqMsg", skip_serializing_if = "Option::is_none")]
    pub req_msg: Option<String>,
    #[serde(rename = "reqTime", skip_serializing_if = "Option::is_none")]
    pub req_time: Option<i32>,
    #[serde(rename = "userInfo", skip_serializing_if = "Option::is_none")]
    pub user_info: Option<crate::models::ServerApiParamsPublicUserInfo>,
}

impl ServerApiParamsGroupRequest {
    pub fn new() -> ServerApiParamsGroupRequest {
        ServerApiParamsGroupRequest {
            ex: None,
            group_info: None,
            handle_msg: None,
            handle_result: None,
            handle_time: None,
            handle_user_id: None,
            inviter_user_id: None,
            join_source: None,
            req_msg: None,
            req_time: None,
            user_info: None,
        }
    }
}


