/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerApiParamsUserSendMsgResp {
    #[serde(rename = "clientMsgID", skip_serializing_if = "Option::is_none")]
    pub client_msg_id: Option<String>,
    #[serde(rename = "sendTime", skip_serializing_if = "Option::is_none")]
    pub send_time: Option<i32>,
    #[serde(rename = "serverMsgID", skip_serializing_if = "Option::is_none")]
    pub server_msg_id: Option<String>,
}

impl ServerApiParamsUserSendMsgResp {
    pub fn new() -> ServerApiParamsUserSendMsgResp {
        ServerApiParamsUserSendMsgResp {
            client_msg_id: None,
            send_time: None,
            server_msg_id: None,
        }
    }
}


