/*
 * 采购系统
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccountCheckRespSingleUserStatus {
    #[serde(rename = "accountStatus", skip_serializing_if = "Option::is_none")]
    pub account_status: Option<String>,
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl UserAccountCheckRespSingleUserStatus {
    pub fn new() -> UserAccountCheckRespSingleUserStatus {
        UserAccountCheckRespSingleUserStatus {
            account_status: None,
            user_id: None,
        }
    }
}


